#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'results'

import os.path, sys

sys.path.append('..')
from dagmctesting import *


DagmcTestContext.intcases = xrange(1,75)

def setup_testcases( self ):
    self.allcases = ['{0:02d}'.format( c ) for c in self.intcases ]
    self.env.XSDIR='../../keffdir1'

DagmcTestContext.setup_testcases = setup_testcases

def get_case_definition( self, casename ):
    case = DagmcTestContext.CaseDefn()
    case.name = casename
    case.runname = 'test{0}.'.format(casename)

    def output_template( t ):
        return 'Templates/Linux/1e-4/{0}{1}'.format(t, casename)

    # Defaults for all cases
    case.inputs['inp'] = 'Inputs/prob{0}i'.format(casename)
    
    if self.options.facet_inputs: 
        case.inputs['gcad'] = 'geom_h5m/1E-4_inp{0}i.h5m'.format( casename )
    else:
        case.inputs['gcad'] = 'geom_sat/geom{0}i.sat'.format( casename )
        case.flags.append( 'ftol=1e-4' )


    case.outputs['o'] = output_template( 'outp' ) 

    return case

DagmcTestContext.get_case_definition = get_case_definition

