#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'results'

import os.path, sys

sys.path.append('..')
from dagmctesting import *


DagmcTestContext.intcases = xrange(1,16)

def setup_testcases( self ):
    self.allcases = ['{0:02d}'.format( c ) for c in self.intcases ]


DagmcTestContext.setup_testcases = setup_testcases

def get_case_definition( self, casename ):
    case = DagmcTestContext.CaseDefn()
    case.name = casename
    case.runname = 'test{0}.'.format(casename)

    def output_template( t ):
        return 'cases/{1}/ref.dag.{0}'.format(t, casename)

    # Defaults for all cases
    case.inputs['inp'] = 'cases/{0}/ref.dag.inp'.format(casename)
    
    if self.options.facet_inputs: 
        case.inputs['gcad'] = 'cases/{0}/ref.geom.h5m'.format( casename )
    else:
        case.inputs['gcad'] = 'cases/{0}/ref.geom.sat'.format( casename )
        case.flags.append( 'ftol=1e-5' )


    case.outputs['m'] = output_template( 'mctal' )
    case.outputs['o'] = output_template( 'out' ) 

    return case

DagmcTestContext.get_case_definition = get_case_definition

